#!/bin/bash
# ============================================================================
# package_installer.sh - 生成 Windows 安装包 LogicAnalyzer_Setup.exe
# 用法:
#   ./package_installer.sh          # 编译 + 打包 + 生成安装包
#   ./package_installer.sh --skip-build  # 跳过编译，直接生成安装包
# ============================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build_cmake"
DIST_DIR="${SCRIPT_DIR}/dist/LogicAnalyzer"
SETUP_NAME="LogicAnalyzer_Setup"
SKIP_BUILD=0

for arg in "$@"; do
    case $arg in
        --skip-build) SKIP_BUILD=1 ;;
    esac
done

# --- 编译 + 打包 ---
if [ $SKIP_BUILD -eq 0 ]; then
    echo ">>> 步骤 1/3: 编译 + 打包..."
    bash "${SCRIPT_DIR}/build.sh" --clean --package
else
    if [ ! -f "${DIST_DIR}/LogicAnalyzer.exe" ]; then
        echo "[错误] 未找到 ${DIST_DIR}/LogicAnalyzer.exe，请先 ./build.sh --package"
        exit 1
    fi
    echo ">>> 跳过编译，使用已有 dist/LogicAnalyzer/"
fi

# --- 检查 NSIS ---
if ! command -v makensis &>/dev/null; then
    echo ">>> 安装 NSIS..."
    pacman -S --needed --noconfirm mingw-w64-x86_64-nsis
fi

# --- 生成 NSIS 脚本 ---
echo ">>> 步骤 2/3: 生成安装脚本..."

VERSION=0.2
OUTPUT="${DIST_DIR}/${SETUP_NAME}.exe"
NSIS_SCRIPT="${DIST_DIR}/setup.nsi"

# Convert paths to Windows format for NSIS (makensis is a Windows exe)
WIN_DIST_DIR=$(cygpath -w "${DIST_DIR}" | sed 's/\\/\\\\/g')
WIN_OUTPUT=$(cygpath -w "${DIST_DIR}/${SETUP_NAME}.exe" | sed 's/\\/\\\\/g')

cat > "${NSIS_SCRIPT}" << NSIEOF
; LogicAnalyzer Windows Setup
; Auto-generated by package_installer.sh

!include "MUI2.nsh"

Name "LogicAnalyzer"
OutFile "${WIN_OUTPUT}"
InstallDir "\$PROGRAMFILES64\LogicAnalyzer"
RequestExecutionLevel admin

!define MUI_ABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

Section "Install"
    SetOutPath \$INSTDIR

    File /r "${WIN_DIST_DIR}\\*"

    CreateDirectory "\$SMPROGRAMS\LogicAnalyzer"
    CreateShortCut "\$SMPROGRAMS\LogicAnalyzer\LogicAnalyzer.lnk" "\$INSTDIR\run.bat" "" "\$INSTDIR\LogicAnalyzer.exe"
    CreateShortCut "\$SMPROGRAMS\LogicAnalyzer\Uninstall.lnk" "\$INSTDIR\uninstall.exe"

    CreateShortCut "\$DESKTOP\LogicAnalyzer.lnk" "\$INSTDIR\run.bat" "" "\$INSTDIR\LogicAnalyzer.exe"

    WriteUninstaller "\$INSTDIR\uninstall.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\LogicAnalyzer" \
        "DisplayName" "LogicAnalyzer"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\LogicAnalyzer" \
        "UninstallString" "\$INSTDIR\uninstall.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\LogicAnalyzer" \
        "DisplayVersion" "${VERSION}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\LogicAnalyzer" \
        "Publisher" "Q2H2"
SectionEnd

Section "Uninstall"
    Delete "\$INSTDIR\uninstall.exe"
    RMDir /r "\$INSTDIR"

    Delete "\$SMPROGRAMS\LogicAnalyzer\LogicAnalyzer.lnk"
    Delete "\$SMPROGRAMS\LogicAnalyzer\Uninstall.lnk"
    RMDir "\$SMPROGRAMS\LogicAnalyzer"

    Delete "\$DESKTOP\LogicAnalyzer.lnk"

    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\LogicAnalyzer"
SectionEnd
NSIEOF

# --- 生成安装包 ---
echo ">>> 步骤 3/3: 生成安装包..."
cd "${DIST_DIR}"
makensis setup.nsi

echo ""
echo "============================================"
echo " 安装包生成完成！"
echo " ${OUTPUT}"
echo "============================================"
